"""Ascend module catalog.

Lesson content is imported from focused lesson modules while the API-facing
MODULES structure remains unchanged.
"""
from .module0 import LESSONS as MODULE_0_LESSONS
from .module1 import LESSONS as MODULE_1_LESSONS
from .module2 import LESSONS as MODULE_2_LESSONS

MODULE_DEFINITIONS = [{'id': 'module-0',
  'number': 0,
  'title': 'DevOps Foundations and Systems Thinking',
  'subtitle': 'Build the mindset before learning the tools.',
  'status': 'active'},
 {'id': 'module-1',
  'number': 1,
  'title': 'Git and Collaborative Source Control',
  'subtitle': 'Repositories, commits, branches, merges, pull requests, tags, and recovery.',
  'status': 'active'},
 {'id': 'module-2',
  'number': 2,
  'title': 'Linux and the Command Line',
  'subtitle': 'Filesystems, users, permissions, processes, services, logs, SSH, and shell fundamentals.',
  'status': 'active'},
 {'id': 'module-3',
  'number': 3,
  'title': 'Networking and Web Fundamentals',
  'subtitle': 'DNS, TCP/IP, HTTP, TLS, ports, routing, proxies, and firewalls.',
  'status': 'locked'},
 {'id': 'module-4',
  'number': 4,
  'title': 'Docker and Containers',
  'subtitle': 'Images, containers, Dockerfiles, Compose, volumes, networks, registries, tags, and rollback.',
  'status': 'locked'},
 {'id': 'module-5',
  'number': 5,
  'title': 'CI/CD Pipelines',
  'subtitle': 'Automated testing, builds, artifacts, deployment strategies, and pipeline troubleshooting.',
  'status': 'locked'},
 {'id': 'module-6',
  'number': 6,
  'title': 'AWS and Cloud Fundamentals',
  'subtitle': 'IAM, billing safety, EC2, S3, VPC, RDS, CloudWatch, ECS, and application deployment.',
  'status': 'locked'},
 {'id': 'module-7',
  'number': 7,
  'title': 'Infrastructure as Code',
  'subtitle': 'Terraform fundamentals, state, modules, environments, and safe infrastructure changes.',
  'status': 'locked'},
 {'id': 'module-8',
  'number': 8,
  'title': 'Monitoring, Logging, and Reliability',
  'subtitle': 'Metrics, logs, traces, health checks, dashboards, alerts, incidents, and postmortems.',
  'status': 'locked'},
 {'id': 'module-9',
  'number': 9,
  'title': 'Security and Secrets',
  'subtitle': 'Least privilege, secret management, patching, vulnerability awareness, HTTPS, and secure '
              'delivery.',
  'status': 'locked'},
 {'id': 'module-10',
  'number': 10,
  'title': 'Capstone Deployment',
  'subtitle': 'Build, deploy, monitor, document, and recover a complete production-style application.',
  'status': 'locked'}]

MODULES = [
    {**MODULE_DEFINITIONS[0], "lessons": MODULE_0_LESSONS},
    {**MODULE_DEFINITIONS[1], "lessons": MODULE_1_LESSONS},
    {**MODULE_DEFINITIONS[2], "lessons": MODULE_2_LESSONS},
    {**MODULE_DEFINITIONS[3], "lessons": []},
    {**MODULE_DEFINITIONS[4], "lessons": []},
    {**MODULE_DEFINITIONS[5], "lessons": []},
    {**MODULE_DEFINITIONS[6], "lessons": []},
    {**MODULE_DEFINITIONS[7], "lessons": []},
    {**MODULE_DEFINITIONS[8], "lessons": []},
    {**MODULE_DEFINITIONS[9], "lessons": []},
    {**MODULE_DEFINITIONS[10], "lessons": []},
]
